name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup default nightly
    - run: cargo build --verbose
      
  test:

    runs-on: ubuntu-latest
    name: Run tests
    
    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup default nightly
    - run: cargo test --verbose
